root = "."
tmp_dir = "temp"

[build]
pre_cmd = ["templ generate"]
cmd = "go build -o ./temp/main.exe main.go"
post_cmd = []
bin = "./temp/main.exe"
full_bin = ""
args_bin = []
include_ext = ["go", "templ"]
exclude_dir = ["temp", "vendor"]
include_dir = []
include_file = []
exclude_file = []
exclude_regex = [".*_templ\\.go$"]
exclude_unchanged = true
follow_symlink = true
log = "crash.log"
poll = false
poll_interval = 500
delay = 500
stop_on_error = false
send_interrupt = false
kill_delay = 500
rerun = true
rerun_delay = 500

[log]
time = false
main_only = false
silent = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = false
